### ISSUE TITLE
ALL FILES 

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.id-id#1]
All files in image folder are untranslated yet

To use active sentence form, not imperative form, especially in the header and sub-header.
To recheck whether the apps/software is already translated/localized as well. If it's not translated, please use the English instead.
To recheck and assess whether it's a programming language and string that should not be translated. Please translate if it's not a programming language. Please rereview the instruction and guideline to differentiate the same.
If unsure, it's safely to leave in English. However, if it's preferred to do so, please make sure everything is treated the same.

**Comment by stonezy123** [comment]
The locfile shown Blocked status, so I re-set Prehandoff status, waiting for checked In.[ ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BSS0xMDI8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7SW5kb25lc2lhbiAoSW5kb25lc2lhKTwvUVI%2bPFFSIElkPSI0IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztDb250ZW50IFR5cGU7RXF1YWw7QXJ0PC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by stonezy123** [comment]
Now, all locfile check in and translated.
